### ISSUE TITLE
SciHub网页不起作用

### ISSUE THREAD

**Issue by xunwu007** [symant233/PublicTools#10]
大佬你好，感谢你编写Beautify这个插件。但这个插件在SciHub的镜像网站里不起作用，暴力猴也没显示该插件在scihub页面被启用了。请问这是怎么回事呢？

**Comment by symant233** [comment]
你好，匹配规则是 `https://*sci-hub.*/*`，我好久没用了，你访问的网址可以提供下吗

**Comment by xunwu007** [comment]
> 你好，匹配规则是 `https://*sci-hub.*/*`，我好久没用了，你访问的网址可以提供下吗

感谢你的回复，我用的网址是https://sci-hub.gupiaoq.com/，感觉是符合你的规则的，但确实在这个页面此脚本未激活

**Comment by symant233** [comment]
![image](https://github.com/user-attachments/assets/a3185e64-895a-419b-ad1e-d49fdc52f13f)
我这里访问是能加载，不过这个网站的样式和[我用的](https://sci-hub.ru/)不一样，脚本里的代码加载了也不会起任何作用：
```js
if (/.*sci-hub.+/.test(location.hostname)) {
        GM_addStyle('#rollback img{width:50px !important;height:50px;margin-left:12px;}');
    };
```
这段代码只是把收起侧边栏时的展开图标缩小。

**Comment by xunwu007** [comment]
因为常用的sci-hub网站及镜像网站我有时能访问，但多数时候又不能访问，所以找来找去找到了上面那个网址。两个网站里页面样式确实不一样，我提供的这个网址侧边栏不能收起，这个确实不好解决。不过我使用https://www.sci-hub.ru/打开scihub，侧边栏能收起，油猴还是显示没有运行中的脚本（不过倒是不咋影响，我的主要需求其实是能收起侧边栏）。不管怎么样，还是很感谢大佬的脚本

**Comment by symant233** [comment]
好的，不过没起用应该只有两个可能，脚本没有更新到最新，或者是没有在油猴的设置里启用该脚本。祝学业顺利！
