### ISSUE TITLE
dblp插件在查看引用或被引论文时不触发

### ISSUE THREAD

**Issue by AkaYoi** [symant233/PublicTools#2]
例如这个：https://dblp.org/rec/journals/fgcs/KoroniotisMST19.html

将const targetNode = document.querySelector('.publ-list');
改成const targetNode = document.querySelector('#main');
就正常了

**Comment by symant233** [comment]
貌似不是这个原因，该页面的论文列表不是动态加载的就没被`MutationObserver`监测到。
外面调用一下`tagging`函数就好了，马上更新。

**Comment by AkaYoi** [comment]
好的，非常感谢

**Comment by symant233** [comment]
搞错了 你说的是References那个要勾选才会加载的😵‍💫，雀食改成#main就行，谢谢了🥳

**Comment by AkaYoi** [comment]
😄是的。还是非常感谢你写了这个工具，肥肠好用🥳，节约了很多很多时间。
