### ISSUE TITLE
photopea 仅隐藏了广告 但是会遮挡操作窗口

### ISSUE THREAD

**Issue by Sev73n** [symant233/PublicTools#5]
![image](https://user-images.githubusercontent.com/16495885/221211684-4ac0b676-f95e-43b9-87c6-85195f9acd4f.png)
如图 右侧的部分被遮挡了 感觉像广告的div遮盖在了操作窗口上面

**Comment by symant233** [comment]
已经定位原因，今天会更新下代码

**Comment by symant233** [comment]
v0.0.46已修复
https://greasyfork.org/zh-CN/scripts/390421-beautify
